---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      patch-minor-action-updates:
        update-types:
          - patch
          - minor
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
