---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      patch-minor-action-updates:
        update-types:
          - patch
          - minor
  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: daily
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: weekly
