name: Validate Requirements
description: Validates YAML requirement files against a JSON schema

inputs:
  schema-path:
    description: Path to the JSON schema file
    required: true
  requirements-dir:
    description: Directory containing YAML requirement files
    required: true

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: "3.12"

    - name: Install dependencies
      shell: bash
      run: pip install jsonschema pyyaml

    - name: Validate requirements
      shell: bash
      run: |
        python ${{ github.action_path }}/validate.py \
          --schema "${{ inputs.schema-path }}" \
          --requirements-dir "${{ inputs.requirements-dir }}"
