name: Generate Requirements PDF
description: Generates a PDF document from YAML requirement files

inputs:
  requirements-dir:
    description: Directory containing YAML requirement files
    required: true
  template-path:
    description: Path to the markdown template
    required: true
  output-path:
    description: Output PDF file path
    required: true

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: "3.12"

    - name: Install dependencies
      shell: bash
      run: |
        pip install pyyaml
        sudo apt-get update && sudo apt-get install -y pandoc texlive-latex-base texlive-latex-recommended texlive-fonts-recommended

    - name: Generate PDF
      shell: bash
      run: |
        python ${{ github.action_path }}/generate.py \
          --requirements-dir "${{ inputs.requirements-dir }}" \
          --template "${{ inputs.template-path }}" \
          --output "${{ inputs.output-path }}"
